/**
 * ZoomSdkProvider.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * ISOLATED — Wraps the @zoom/meetingsdk-react-native SDK in a lazy-loaded,
 * error-safe accessor. All calls go through this provider so the rest of the
 * test module never directly imports from the SDK (which would crash the app in
 * Expo Go before the try/catch can fire).
 *
 * Does NOT import: PlayerAccess, ZoomMeetingPlayer, LiveSessionPlayer,
 * YoutubePlayer, CoursePlayer, or any live-session module.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import { Platform } from 'react-native';
import Constants from 'expo-constants';

export interface ZoomSdkInitOptions {
  jwtToken: string;        // SDK signature / JWT generated by backend
  meetingNumber: string;
  password: string;
  displayName: string;
  sdkKey: string;
}

export interface ZoomSdkResult {
  success: boolean;
  error?: string;
  code?: number | string;
}

let _sdk: any = null;

function getSdk(): any | null {
  if (_sdk) return _sdk;
  try {
    const mod = require('@zoom/meetingsdk-react-native');
    _sdk = mod.ZoomUs || mod.default?.ZoomUs || mod.default;
    return _sdk;
  } catch (e: any) {
    console.warn('[ZoomSdkProvider] SDK not available:', e?.message ?? e);
    return null;
  }
}

/**
 * Initialize the Zoom SDK with the provided credentials.
 * Returns {success: false} gracefully if SDK is unavailable (e.g. Expo Go).
 */
export async function initializeZoomSdk(sdkKey: string, sdkSecret: string): Promise<ZoomSdkResult> {
  const sdk = getSdk();
  if (!sdk) {
    return { success: false, error: 'Zoom SDK native module is not available in this environment (Expo Go / SDK not installed).' };
  }

  try {
    console.log({
      expoSdk: Constants.expoConfig?.sdkVersion,
      executionEnvironment: (Constants as any).executionEnvironment,
      appOwnership: Constants.appOwnership,
      platform: Platform.OS,
    });
    
    const result = await sdk.initialize({ clientKey: sdkKey, clientSecret: sdkSecret, domain: 'zoom.us' });
    
    if (result.result === 'Success' || result.errorCode === 0) {
      console.log("SDK initialized");
      
      // Attempt to attach an event listener for meeting end if the SDK supports it
      try {
        const { NativeEventEmitter, NativeModules } = require('react-native');
        if (NativeModules.RNZoomUs) {
          const zoomEmitter = new NativeEventEmitter(NativeModules.RNZoomUs);
          zoomEmitter.addListener('MeetingEvent', (event: any) => {
            if (event.event === 'ended' || event.event === 'left') {
               console.log("Meeting ended");
            }
          });
        }
      } catch(e) {}
      
      return { success: true };
    }
    return { success: false, error: result.result ?? 'Unknown init error', code: result.errorCode };
  } catch (e: any) {
    console.error('[ZoomSdkProvider] Init error:', e);
    return { success: false, error: e?.message ?? String(e) };
  }
}

/**
 * Join a Zoom meeting using Meeting SDK.
 */
export async function joinZoomMeeting(opts: ZoomSdkInitOptions): Promise<ZoomSdkResult> {
  const sdk = getSdk();
  if (!sdk) {
    return { success: false, error: 'Zoom SDK not available.' };
  }

  try {
    console.log("Meeting joining...");
    const result = await sdk.joinMeeting({
      jwtToken: opts.jwtToken,
      meetingNo: opts.meetingNumber,
      pwd: opts.password,
      displayName: opts.displayName,
      noInvite: true,
      noShare: false,
      noVideo: false,
      noAudio: false,
    });

    if (result.result === 'Success' || result.errorCode === 0) {
      console.log("Meeting joined");
      return { success: true };
    }

    console.log("Meeting failed", result.result);
    return { success: false, error: result.result ?? 'Join failed', code: result.errorCode };
  } catch (e: any) {
    console.log("Meeting failed", e);
    return { success: false, error: e?.message ?? String(e) };
  }
}

/**
 * Check whether the native module is loaded.
 */
export function isZoomSdkLoaded(): boolean {
  return getSdk() !== null;
}
