export const INTERACTION_CONSTANTS = {
  MESSAGE_LIMIT: 100,
  EDIT_WINDOW_MINUTES: 5,
  REACTION_INTERVAL_MS: 2000,
  RECONNECT_DELAY_MS: 3000,
  SSE_TIMEOUT_MS: 30000,
  MAX_ATTACHMENT_SIZE_MB: 25,
};
